runtime: python310        
entrypoint: gunicorn -b :$PORT main:app

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto

env_variables:
  BUCKET_NAME: 'cs163-optadpct.appspot.com'